var onUncaughtException = function(error){
    console.log('예외가 발생했군...');
}

process.on('uncaughtException', onUncaughtException);

var test = function(){
    setTimeout(test,2000);
    error.error.error();
};
setTimeout(test,2000);